packaging_format = 2

id = "galette"
name = "Galette"
description.en = "Membership management web application for non profit organizations"
description.fr = "Outil de gestion d'adhérents et de cotisation en ligne pour associations"

version = "0.9.6.1~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.galette.eu"
demo = "https://demo.galette.eu/login"
admindoc = "https://doc.galette.eu/fr/master/"
code = "https://github.com/galette/galette"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/galette"

    [install.init_main_permission]
    help.en = "If enabled, Galette will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Galette sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.database]
    ask.en = "Choose SQL databe you want"
    type = "select"
    choices = ["pgsql", "mysql"]
    default = "pgsql"

[resources]
        [resources.sources.main]
        url = "https://download.tuxfamily.org/galette/galette-0.9.6.1.tar.bz2"
        sha256 = "7f3d09af19711372cc35d48352e115ee96e835ea879298347289d274308bb011"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php7.4-tidy, php7.4-intl, php7.4-mbstring, php7.4-xml, php7.4-gd, php7.4-curl"

    packages_from_raw_bash = """
    if [[ "$database" == "mysql" ]]; then 
        echo "mariadb-server, php7.4-mysql"
            
    elif [[ "$database" == "postgresql" ]]; then
        echo "postgresql, postgresql-contrib, php7.4-psql"
    fi
    """
