#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "galette"
name = "Galette"
description.en = "Membership management web application for non profit organizations"
description.fr = "Outil de gestion d'adhérents et de cotisation en ligne pour associations"

version = "1.1.3~ynh2"

maintainers = []

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.galette.eu"
demo = "https://demo.galette.eu/login"
admindoc = "https://doc.galette.eu/fr/master/"
code = "https://github.com/galette/galette"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/galette"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.db_type]
     ask.fr = "quel moteur de base de données souhaitez-vous"
     ask.en = "which data base engine do you prefer"
     help.fr : "Si vous ne savez pas quoi chosir, c'est que ça n'a aucune importance;"
     help.en = "If you don't know what to choose ... don't choose ;-) "
     type = "select"
     choices = ["mysql","postgresql"]
     default = "postgresql"

    [install.tb_prefix]
     ask.fr = "voulez-vous utiliser un préfixe de table différent du défaut (galette_)?"
     ask.help = "si oui, veillez à le terminer par un _ ("souligné", "tiret du 8",...)
     type = "string"
     default = "galette_"
 

[resources]
    [resources.sources.main]
    url = "https://www.galette.eu/download/galette-1.1.3.tar.bz2"
    sha256 = "4797a529e5ba7925a2f265fce30801ca05db515832e6bc00c51413492841993a"

    autoupdate.strategy = "latest_github_tag"
    autoupdate.needs_manual_tweaks = true

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    
    packages = "php8.3-tidy, php8.3-intl, php8.3-mbstring, php8.3-xml, php8.3-gd, php8.3-curl"
    packages_from_raw_bash = """
       if [[ "$db_type" == "mysql" ]]; then 
   	  echo "mariadb-server, php8.3-mysql"
       fi
       elif [[ "$db_type" == "postgresql" ]]; then
            echo "postgresql, php8.3-pgsql"
       fi
    """


# seulement une de ces lignes est possible. Peut-on faire ça par un test ? ou suffit-il d'initialiser la base dans le scriot d'install ?
#    [resources.database]
#     type = "mysql"
#     type = "postgresql"
